metiers:
  mineur:
    '1':
      - '27215'
      - '27216'
      - '27217'
    '2':
      - '27210'
      - '27218'
      - '27226'
    '3':
      - '27229'
    '4':
      - '27227'
    '5':
      - '27228'
  bucheron:
    '1':
      - '26973'
      - '27186'
    '2':
      - '27239'
    '3':
      - '27208'
      - '27240'
    '4':
      - '1819'
    '5':
      - '1820'
  chasseur:
    '1':
      - '383:92'
      - '383:90'
      - '383:93'
    '2':
      - '383:91'
      - '383:95'
      - '383:94'
      - '383:52'
    '3':
      - '383:100'
      - '383:98'
    '4':
      - '383:99'
      - '383:55'
      - '383:50'
    '5':
      - '383:4'
      - '383:65'
  agriculteur:
    '1':
      - '27195'
      - '27195:4'
    '2':
      - '27193:14'
      - '27193:11'
    '3':
      - '27191'
      - '27192'
    '4':
      - '27187'
      - '27189'
    '5':
      - '27188'
  dresseur:
    '1':
      - '383:92'
      - '383:90'
      - '383:93'
    '2':
      - '383:94'
      - '383:52'
      - '383:91'
      - '383:95'
    '3':
      - '383:100'
    '4':
      - '383:55'
      - '383:65'
    '5':
      - '383:65'
  mafieux:
    '1':
      - '23846'
    '2':
      - '23830'
    '3':
      - '23812'
    '4':
      - '23838'
      - '23836'
    '5':
      - '23834'
  policier:
    '1':
      - '23842'
    '2':
      - '23814'
      - '23830'
    '3':
      - '23828'
    '4':
      - '23838'
    '5':
      - '23834'
  forgeron:
    '1':
      - '1816'
      - '1817'
    '2':
      - '1814'
    '3':
      - '1821'
      - '1813'
    '4':
      - '1815'
    '5':
      - '1818'
  ingenieur:
    '1':
      - '27215'
      - '27216'
      - '27217'
    '2':
      - '27210'
      - '27218'
      - '27226'
    '3':
      - '27229'
    '4':
      - '27227'
    '5':
      - '27228'
  alchimiste:
    '1':
      - '27195'
      - '27195:4'
    '2':
      - '27193:14'
      - '27193:11'
    '3':
      - '27191'
      - '27192'
    '4':
      - '27187'
      - '27189'
    '5':
      - '27188'